MovieCenter/MovieCenter/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home),
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
]

MovieCenter/movies/urls.py
from django.urls import path
from . import views


app_name = 'movies'


urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_id>', views.detail, name='detail')
]

MovieCenter/movies/models.py
from django.db import models
from django.utils import timezone

class Genre(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name





class Movie(models.Model):
    title = models.CharField(max_length=255)
    release_year = models.IntegerField()
    rate_limit = models.CharField(max_length=255)
    duration = models.FloatField()
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    date_created = models.DateTimeField(default = timezone.now)

MovieCenter/MovieCenter/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home.html')

MovieCenter/movies/views.py
from django.http import HttpResponse,Http404
from django.shortcuts import render, get_object_or_404
from .models import Movie
# Create your views here.


def index(request):
    movies = Movie.objects.all()
    return render(request, 'movies/index.html', {'movies':movies})

def detail(request, movie_id):
    movie = get_object_or_404(Movie, id=movie_id)
    return render(request, 'movies/detail.html', {'movie':movie})

MovieCenter/movies/templates/movies/detail.html
{% extends 'base.html' %}
{% block content %}
    <dl>
        <dt>Title</dt>
        <dd>{{ movie.title }}</dd>
        <dt>Genre</dt>
        <dd>{{ movie.genre }}</dd>
        <dt>Release Year</dt>
        <dd>{{ movie.release_year }}</dd>
        <dt>Rate Limit</dt>
        <dd>{{ movie.rate_limit }}</dd>
    </dl>
{% endblock %}

MovieCenter/movies/templates/movies/index.html
{% extends 'base.html' %}

{% block content %}
    <table class="table table-bordered table-hover">
        <thead>
        <tr>
            <th>Title</th>
            <th>Genre</th>
            <th>Release Year</th>
            <th>Rate Limit</th>
        </tr>
        </thead>
        <tbody>
            {% for movie in movies %}

                <tr>
                    <td>
                        <a href="{% url 'movies:detail' movie.id %}">{{ movie.title }}</a>
                    </td>
                    <td>{{ movie.genre }}</td>
                    <td>{{ movie.release_year }}</td>
                    <td>{{ movie.rate_limit }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

MovieCenter/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <title>MovieCenter</title>
  </head>
  <body>
      <nav class="navbar navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">MovieCenter</a>
      </div>
      </nav>
      <main class="container">
          {% block content %}
          {% endblock %}
      </main>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
    -->
  </body>
</html>

MovieCenter/templates/home.html
{% extends 'base.html' %}

{% block content %}
    <a href="{% url 'movies:index' %}">Movies</a>
{% endblock %}